// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Addreceipe: typeof import('./src/components/layout/addreceipe.vue')['default']
    AddReceipe: typeof import("./src/components/layout/AddReceipe.vue")["default"]
    Buttons: typeof import('./src/components/layout/buttons.vue')['default']
    Card: typeof import('./src/components/layout/card.vue')['default']
    Display: typeof import('./src/components/layout/display.vue')['default']
    Empty: typeof import('./src/components/layout/empty.vue')['default']
    Error: typeof import('./src/components/layout/error.vue')['default']
    Extra: typeof import('./src/components/layout/extra.vue')['default']
    Favourites: typeof import('./src/components/layout/favourites.vue')['default']
    Filter: typeof import('./src/components/layout/filter.vue')['default']
    Footerbar: typeof import('./src/components/layout/footerbar.vue')['default']
    FooterBar: typeof import("./src/components/layout/footerBar.vue")["default"]
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Like: typeof import("./src/components/layout/like.vue")["default"]
    Navbar: typeof import('./src/components/layout/navbar.vue')['default']
    NavBar: typeof import("./src/components/layout/NavBar.vue")["default"]
    Profile: typeof import('./src/components/layout/profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signin: typeof import('./src/components/layout/signin.vue')['default']
    SignIn: typeof import("./src/components/layout/SignIn.vue")["default"]
    Signup: typeof import('./src/components/layout/signup.vue')['default']
    SignUp: typeof import("./src/components/layout/SignUp.vue")["default"]
    Userprofile: typeof import('./src/components/layout/userprofile.vue')['default']
    UserProfile: typeof import("./src/components/layout/UserProfile.vue")["default"]
  }
}
