-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE FUNCTION AVG(rating text)
-- RETURNS SETOF ratings AS $$
--     SELECT AVG(rating)
--     FROM ratings
-- $$ LANGUAGE sql STABLE;
