-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.averagerating()
--  RETURNS SETOF ratings
--  LANGUAGE sql
--  STABLE
-- AS $$
--   SELECT AVG(rating)
--   FROM ratings
-- $$;
