-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE ratings
-- ALTER COLUMN rating TYPE double precision
-- USING rating::double precision;
